# Generated by Django 5.2 on 2025-08-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=255)),
                ('patient_FullName', models.CharField(max_length=30)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('disease', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
