# Generated by Django 5.2 on 2025-08-29 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
