# Generated by Django 5.2 on 2025-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0002_alter_patient_visit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bite_wings', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('opg', models.BooleanField(default=True)),
                ('PA', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
            ],
        ),
    ]
