# Generated by Django 5.2 on 2025-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0003_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='patient',
            field=models.ManyToManyField(to='clinic_records.patient'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='picture_note',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pictures_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True),
        ),
    ]
