# Generated by Django 5.2 on 2025-09-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0004_pictures_patient_pictures_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalingProphy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_count', models.IntegerField()),
                ('scalingprophy_price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('scalingprophy_note', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture_note',
            field=models.TextField(default=None),
        ),
    ]
