# Generated by Django 5.2 on 2025-09-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0005_scalingprophy_alter_pictures_picture_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='bite_wings',
        ),
        migrations.AddField(
            model_name='pictures',
            name='bite_wing1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='bite_wing2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='bite_wing3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='bite_wing4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='PA',
            field=models.CharField(max_length=1),
        ),
    ]
