# Generated by Django 5.2 on 2025-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0006_remove_pictures_bite_wings_pictures_bite_wing1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scalingprophy',
            name='sessions_count',
            field=models.BooleanField(choices=[('one', 'one session'), ('two', 'two sessions')]),
        ),
    ]
