# Generated by Django 5.2 on 2025-09-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_records', '0007_alter_scalingprophy_sessions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='PA',
        ),
        migrations.AddField(
            model_name='pictures',
            name='PA1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='PA2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='PA3',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='PA4',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
